#cloud-config
ssh_pwauth: no
users:
  - name: netzen
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    lock_passwd: true
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBSDOPWi2De9QKoyrkQn6/zOesiYS4AMEQ9KZyE4oR+Z netzen@MacBook-Pro--netzen.local
write_files:
- path: /va/prometheus.yml
  content: |
    routes:
      - input:
          plugin: metrics_pull 
          config:
            url: http://localhost:9090/metrics
            format:
              prometheus: {}
        channel:
          channel_ref:
            name: cloud_monitoring
- path: /etc/nginx/conf.d/default.conf
  content: |
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=cache:10m inactive=60m;
    upstream hosts {
    	server ${shs_address_0};
    	server ${shs_address_1};
    }
    server {
    	listen 80;
        server_name shs.netzen.dev;
    	location /long_dummy {
    		proxy_pass http://hosts; 
    		proxy_cache cache;
    		proxy_cache_valid any 10m;
    		add_header X-Proxy-Cache $upstream_cache_status;
    	}
    	location / {
    		proxy_pass http://hosts;
    	}
      location /nginx-status {
        stub_status on;
      }
    }