version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"    
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  shs:
    build:
      context: ..
      dockerfile: shs/Dockerfile
    ports:
      - "80:33207"
    depends_on:
      - db

volumes:
  db_data: