version: '3.3'
services:

  db:
    image: "docker.io/postgres:16.1-alpine3.18"
    ports:
      - "5432:5432"    
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/

  unifiedagent:
    container_name: unifiedagent 
    image: "cr.yandex/yc/unified-agent" 
    environment:
      FOLDER_ID: "${folder_id}"
    restart: always 
    network_mode: "host" 
    volumes:
      - /ua:/etc/yandex/unified_agent/conf.d

volumes:
  db_data: