#cloud-config
ssh_pwauth: no
users:
  - name: netzen
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    lock_passwd: true
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBSDOPWi2De9QKoyrkQn6/zOesiYS4AMEQ9KZyE4oR+Z netzen@MacBook-Pro--netzen.local
write_files:
- content: |
    routes:
      - input:
          plugin: metrics_pull 
          config:
            url: http://localhost:9090/metrics
            format:
              prometheus: {}
        channel:
          channel_ref:
            name: cloud_monitoring
  path: /va/prometheus.yml
- content: |
    student_email: netzen@yandex.ru
    postgres_cluster:
      hosts:
      - address: ${db_address}
      port: 5432
    user: postgres
    password: postgres
    db_name: postgres
    ssl_mode: disable
    use_closest_node: false
  path: /opt/bingo/config.yaml
- content: |
    create log dir
  path: /opt/bongo/logs/b6c82e0feb/create.dir