version: '3.3'
services:

  nginx:
    image: docker.io/openresty/openresty:jammy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d/:/etc/nginx/conf.d/
      - /etc/letsencrypt/live/shs.netzen.dev/:/etc/letsencrypt/live/shs.netzen.dev/
